# Generated by Django 5.0.6 on 2024-08-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='code',
            field=models.IntegerField(default=0),
        ),
    ]
